log_level: debug

tide:
  merge_method:
    Azure/genesys: squash
    Azure/aks-engine: squash
  queries:
  - repos:
    - Azure/genesys
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
  - repos:
    - Azure/aks-engine
    labels:
    - lgtm
    - approved
    missingLabels:
    - needs-ok-to-test
    - DO-NOT-MERGE
    - do-not-merge/work-in-progress
    - do-not-merge/hold
